package www.tw

import scala.annotation.unused

case class Tailwind() {
  def hover(@unused styles: Tailwind): Tailwind       = this
  def focus(@unused styles: Tailwind): Tailwind       = this
  def focusWithin(@unused styles: Tailwind): Tailwind = this
  def active(@unused styles: Tailwind): Tailwind      = this
  def groupHover(@unused styles: Tailwind): Tailwind  = this
  def groupFocus(@unused styles: Tailwind): Tailwind  = this
  def before(@unused styles: Tailwind): Tailwind      = this
  def after(@unused styles: Tailwind): Tailwind       = this
  def last(@unused styles: Tailwind): Tailwind        = this
  def lastOfType(@unused styles: Tailwind): Tailwind  = this
  def sm(@unused styles: Tailwind): Tailwind          = this
  def md(@unused styles: Tailwind): Tailwind          = this
  def lg(@unused styles: Tailwind): Tailwind          = this
  def xl(@unused styles: Tailwind): Tailwind          = this
  def group: Tailwind                                 = this
  def pointerEventsNone: Tailwind                     = this
  def pointerEventsAuto: Tailwind                     = this
  def visible: Tailwind                               = this
  def invisible: Tailwind                             = this
  def static: Tailwind                                = this
  def fixed: Tailwind                                 = this
  def absolute: Tailwind                              = this
  def relative: Tailwind                              = this
  def sticky: Tailwind                                = this
  def inset0: Tailwind                                = this
  def top0: Tailwind                                  = this
  def right0: Tailwind                                = this
  def bottom0: Tailwind                               = this
  def left0: Tailwind                                 = this
  def z0: Tailwind                                    = this
  def z1: Tailwind                                    = this
  def z2: Tailwind                                    = this
  def z3: Tailwind                                    = this
  def z4: Tailwind                                    = this
  def z5: Tailwind                                    = this
  def z999: Tailwind                                  = this
  def z9999: Tailwind                                 = this
  def zAuto: Tailwind                                 = this
  def m0: Tailwind                                    = this
  def m2: Tailwind                                    = this
  def m4: Tailwind                                    = this
  def m6: Tailwind                                    = this
  def m8: Tailwind                                    = this
  def m12: Tailwind                                   = this
  def m16: Tailwind                                   = this
  def m20: Tailwind                                   = this
  def m24: Tailwind                                   = this
  def m32: Tailwind                                   = this
  def m40: Tailwind                                   = this
  def m48: Tailwind                                   = this
  def mAuto: Tailwind                                 = this
  def mx0: Tailwind                                   = this
  def mx2: Tailwind                                   = this
  def mx4: Tailwind                                   = this
  def mx6: Tailwind                                   = this
  def mx8: Tailwind                                   = this
  def mx12: Tailwind                                  = this
  def mx16: Tailwind                                  = this
  def mx20: Tailwind                                  = this
  def mx24: Tailwind                                  = this
  def mx32: Tailwind                                  = this
  def mx40: Tailwind                                  = this
  def mx48: Tailwind                                  = this
  def mxAuto: Tailwind                                = this
  def my0: Tailwind                                   = this
  def my2: Tailwind                                   = this
  def my4: Tailwind                                   = this
  def my6: Tailwind                                   = this
  def my8: Tailwind                                   = this
  def my12: Tailwind                                  = this
  def my16: Tailwind                                  = this
  def my20: Tailwind                                  = this
  def my24: Tailwind                                  = this
  def my32: Tailwind                                  = this
  def my40: Tailwind                                  = this
  def my48: Tailwind                                  = this
  def myAuto: Tailwind                                = this
  def mt0: Tailwind                                   = this
  def mt2: Tailwind                                   = this
  def mt4: Tailwind                                   = this
  def mt6: Tailwind                                   = this
  def mt8: Tailwind                                   = this
  def mt12: Tailwind                                  = this
  def mt16: Tailwind                                  = this
  def mt20: Tailwind                                  = this
  def mt24: Tailwind                                  = this
  def mt32: Tailwind                                  = this
  def mt40: Tailwind                                  = this
  def mt48: Tailwind                                  = this
  def mtAuto: Tailwind                                = this
  def mr0: Tailwind                                   = this
  def mr2: Tailwind                                   = this
  def mr4: Tailwind                                   = this
  def mr6: Tailwind                                   = this
  def mr8: Tailwind                                   = this
  def mr12: Tailwind                                  = this
  def mr16: Tailwind                                  = this
  def mr20: Tailwind                                  = this
  def mr24: Tailwind                                  = this
  def mr32: Tailwind                                  = this
  def mr40: Tailwind                                  = this
  def mr48: Tailwind                                  = this
  def mrAuto: Tailwind                                = this
  def mb0: Tailwind                                   = this
  def mb2: Tailwind                                   = this
  def mb4: Tailwind                                   = this
  def mb6: Tailwind                                   = this
  def mb8: Tailwind                                   = this
  def mb12: Tailwind                                  = this
  def mb16: Tailwind                                  = this
  def mb20: Tailwind                                  = this
  def mb24: Tailwind                                  = this
  def mb32: Tailwind                                  = this
  def mb40: Tailwind                                  = this
  def mb48: Tailwind                                  = this
  def mbAuto: Tailwind                                = this
  def ml0: Tailwind                                   = this
  def ml2: Tailwind                                   = this
  def ml4: Tailwind                                   = this
  def ml6: Tailwind                                   = this
  def ml8: Tailwind                                   = this
  def ml12: Tailwind                                  = this
  def ml16: Tailwind                                  = this
  def ml20: Tailwind                                  = this
  def ml24: Tailwind                                  = this
  def ml32: Tailwind                                  = this
  def ml40: Tailwind                                  = this
  def ml48: Tailwind                                  = this
  def mlAuto: Tailwind                                = this
  def lineClamp1: Tailwind                            = this
  def lineClamp2: Tailwind                            = this
  def lineClamp3: Tailwind                            = this
  def lineClamp4: Tailwind                            = this
  def lineClamp5: Tailwind                            = this
  def lineClamp6: Tailwind                            = this
  def lineClampNone: Tailwind                         = this
  def block: Tailwind                                 = this
  def inlineBlock: Tailwind                           = this
  def inline: Tailwind                                = this
  def flex: Tailwind                                  = this
  def inlineFlex: Tailwind                            = this
  def flowRoot: Tailwind                              = this
  def table: Tailwind                                 = this
  def inlineTable: Tailwind                           = this
  def grid: Tailwind                                  = this
  def inlineGrid: Tailwind                            = this
  def hidden: Tailwind                                = this
  def sizePx: Tailwind                                = this
  def size8: Tailwind                                 = this
  def size16: Tailwind                                = this
  def size20: Tailwind                                = this
  def size24: Tailwind                                = this
  def size32: Tailwind                                = this
  def size40: Tailwind                                = this
  def size48: Tailwind                                = this
  def size64: Tailwind                                = this
  def size128: Tailwind                               = this
  def size256: Tailwind                               = this
  def sizeFull: Tailwind                              = this
  def hPx: Tailwind                                   = this
  def h8: Tailwind                                    = this
  def h16: Tailwind                                   = this
  def h20: Tailwind                                   = this
  def h24: Tailwind                                   = this
  def h32: Tailwind                                   = this
  def h40: Tailwind                                   = this
  def h48: Tailwind                                   = this
  def h64: Tailwind                                   = this
  def h128: Tailwind                                  = this
  def h256: Tailwind                                  = this
  def hFull: Tailwind                                 = this
  def hScreen: Tailwind                               = this
  def hAuto: Tailwind                                 = this
  def hMin: Tailwind                                  = this
  def hMax: Tailwind                                  = this
  def hCustom1: Tailwind                              = this
  def hCustom2: Tailwind                              = this
  def hCustom3: Tailwind                              = this
  def minHFull: Tailwind                              = this
  def minHScreen: Tailwind                            = this
  def wPx: Tailwind                                   = this
  def w8: Tailwind                                    = this
  def w16: Tailwind                                   = this
  def w20: Tailwind                                   = this
  def w24: Tailwind                                   = this
  def w32: Tailwind                                   = this
  def w40: Tailwind                                   = this
  def w48: Tailwind                                   = this
  def w64: Tailwind                                   = this
  def w128: Tailwind                                  = this
  def w256: Tailwind                                  = this
  def w480: Tailwind                                  = this
  def w512: Tailwind                                  = this
  def w640: Tailwind                                  = this
  def w768: Tailwind                                  = this
  def w1024: Tailwind                                 = this
  def w1536: Tailwind                                 = this
  def wPc10: Tailwind                                 = this
  def wPc20: Tailwind                                 = this
  def wPc25: Tailwind                                 = this
  def wPc30: Tailwind                                 = this
  def wPc33: Tailwind                                 = this
  def wPc40: Tailwind                                 = this
  def wPc50: Tailwind                                 = this
  def wPc60: Tailwind                                 = this
  def wPc66: Tailwind                                 = this
  def wPc70: Tailwind                                 = this
  def wPc75: Tailwind                                 = this
  def wPc80: Tailwind                                 = this
  def wPc90: Tailwind                                 = this
  def wFull: Tailwind                                 = this
  def wScreen: Tailwind                               = this
  def wAuto: Tailwind                                 = this
  def wMin: Tailwind                                  = this
  def wMax: Tailwind                                  = this
  def wFit: Tailwind                                  = this
  def wCustom1: Tailwind                              = this
  def wCustom2: Tailwind                              = this
  def wCustom3: Tailwind                              = this
  def minWFit: Tailwind                               = this
  def minWMin: Tailwind                               = this
  def minWMax: Tailwind                               = this
  def minW0: Tailwind                                 = this
  def maxW128: Tailwind                               = this
  def maxW256: Tailwind                               = this
  def maxW480: Tailwind                               = this
  def maxW512: Tailwind                               = this
  def maxW640: Tailwind                               = this
  def maxW768: Tailwind                               = this
  def maxW1024: Tailwind                              = this
  def maxWFull: Tailwind                              = this
  def maxWCustom1: Tailwind                           = this
  def maxWCustom2: Tailwind                           = this
  def maxWCustom3: Tailwind                           = this
  def maxHInherit: Tailwind                           = this
  def flex1: Tailwind                                 = this
  def flexAuto: Tailwind                              = this
  def flexInitial: Tailwind                           = this
  def flexNone: Tailwind                              = this
  def flexFill: Tailwind                              = this
  def flexGrow: Tailwind                              = this
  def grow: Tailwind                                  = this
  def cursorAuto: Tailwind                            = this
  def cursorDefault: Tailwind                         = this
  def cursorHelp: Tailwind                            = this
  def cursorPointer: Tailwind                         = this
  def cursorText: Tailwind                            = this
  def cursorMove: Tailwind                            = this
  def cursorNotAllowed: Tailwind                      = this
  def cursorCrosshair: Tailwind                       = this
  def cursorEwResize: Tailwind                        = this
  def cursorNsResize: Tailwind                        = this
  def cursorNeswResize: Tailwind                      = this
  def cursorNwseResize: Tailwind                      = this
  def selectNone: Tailwind                            = this
  def selectText: Tailwind                            = this
  def selectAll: Tailwind                             = this
  def selectAuto: Tailwind                            = this
  def resizeNone: Tailwind                            = this
  def resizeY: Tailwind                               = this
  def resizeX: Tailwind                               = this
  def resize: Tailwind                                = this
  def gridCols1: Tailwind                             = this
  def gridCols2: Tailwind                             = this
  def gridCols3: Tailwind                             = this
  def gridCols4: Tailwind                             = this
  def gridCols5: Tailwind                             = this
  def gridCols6: Tailwind                             = this
  def gridCols7: Tailwind                             = this
  def gridCols8: Tailwind                             = this
  def gridCols9: Tailwind                             = this
  def gridCols10: Tailwind                            = this
  def gridCols11: Tailwind                            = this
  def gridCols12: Tailwind                            = this
  def gridColsNone: Tailwind                          = this
  def gridColsSubgrid: Tailwind                       = this
  def gridColsCustom1: Tailwind                       = this
  def gridColsCustom2: Tailwind                       = this
  def gridColsCustom3: Tailwind                       = this
  def gridColsCustom4: Tailwind                       = this
  def flexRow: Tailwind                               = this
  def flexRowReverse: Tailwind                        = this
  def flexCol: Tailwind                               = this
  def flexColReverse: Tailwind                        = this
  def flexWrap: Tailwind                              = this
  def flexWrapReverse: Tailwind                       = this
  def flexNowrap: Tailwind                            = this
  def itemsStart: Tailwind                            = this
  def itemsEnd: Tailwind                              = this
  def itemsCenter: Tailwind                           = this
  def itemsBaseline: Tailwind                         = this
  def itemsStretch: Tailwind                          = this
  def justifyNormal: Tailwind                         = this
  def justifyStart: Tailwind                          = this
  def justifyEnd: Tailwind                            = this
  def justifyCenter: Tailwind                         = this
  def justifyBetween: Tailwind                        = this
  def justifyAround: Tailwind                         = this
  def justifyEvenly: Tailwind                         = this
  def justifyStretch: Tailwind                        = this
  def justifyItemsStart: Tailwind                     = this
  def justifyItemsEnd: Tailwind                       = this
  def justifyItemsCenter: Tailwind                    = this
  def justifyItemsStretch: Tailwind                   = this
  def selfStretch: Tailwind                           = this
  def gap0: Tailwind                                  = this
  def gap2: Tailwind                                  = this
  def gap4: Tailwind                                  = this
  def gap6: Tailwind                                  = this
  def gap8: Tailwind                                  = this
  def gap12: Tailwind                                 = this
  def gap16: Tailwind                                 = this
  def gap20: Tailwind                                 = this
  def gap24: Tailwind                                 = this
  def gap32: Tailwind                                 = this
  def gap40: Tailwind                                 = this
  def gap48: Tailwind                                 = this
  def gapX0: Tailwind                                 = this
  def gapX2: Tailwind                                 = this
  def gapX4: Tailwind                                 = this
  def gapX6: Tailwind                                 = this
  def gapX8: Tailwind                                 = this
  def gapX12: Tailwind                                = this
  def gapX16: Tailwind                                = this
  def gapX20: Tailwind                                = this
  def gapX24: Tailwind                                = this
  def gapX32: Tailwind                                = this
  def gapX40: Tailwind                                = this
  def gapX48: Tailwind                                = this
  def gapY0: Tailwind                                 = this
  def gapY2: Tailwind                                 = this
  def gapY4: Tailwind                                 = this
  def gapY6: Tailwind                                 = this
  def gapY8: Tailwind                                 = this
  def gapY12: Tailwind                                = this
  def gapY16: Tailwind                                = this
  def gapY20: Tailwind                                = this
  def gapY24: Tailwind                                = this
  def gapY32: Tailwind                                = this
  def gapY40: Tailwind                                = this
  def gapY48: Tailwind                                = this
  def spaceX0: Tailwind                               = this
  def spaceX2: Tailwind                               = this
  def spaceX4: Tailwind                               = this
  def spaceX6: Tailwind                               = this
  def spaceX8: Tailwind                               = this
  def spaceX12: Tailwind                              = this
  def spaceX16: Tailwind                              = this
  def spaceX20: Tailwind                              = this
  def spaceX24: Tailwind                              = this
  def spaceX32: Tailwind                              = this
  def spaceX40: Tailwind                              = this
  def spaceX48: Tailwind                              = this
  def spaceY0: Tailwind                               = this
  def spaceY2: Tailwind                               = this
  def spaceY4: Tailwind                               = this
  def spaceY6: Tailwind                               = this
  def spaceY8: Tailwind                               = this
  def spaceY12: Tailwind                              = this
  def spaceY16: Tailwind                              = this
  def spaceY20: Tailwind                              = this
  def spaceY24: Tailwind                              = this
  def spaceY32: Tailwind                              = this
  def spaceY40: Tailwind                              = this
  def spaceY48: Tailwind                              = this
  def spaceYReverse: Tailwind                         = this
  def spaceXReverse: Tailwind                         = this
  def divideX3: Tailwind                              = this
  def divideXDefault: Tailwind                        = this
  def divideY3: Tailwind                              = this
  def divideYDefault: Tailwind                        = this
  def divideYReverse: Tailwind                        = this
  def divideXReverse: Tailwind                        = this
  def divideSolid: Tailwind                           = this
  def divideDashed: Tailwind                          = this
  def divideDotted: Tailwind                          = this
  def divideDouble: Tailwind                          = this
  def divideNone: Tailwind                            = this
  def divideDefault: Tailwind                         = this
  def divideGray0: Tailwind                           = this
  def divideGray1: Tailwind                           = this
  def divideGray2: Tailwind                           = this
  def divideGray3: Tailwind                           = this
  def divideGray4: Tailwind                           = this
  def divideGray5: Tailwind                           = this
  def divideGray6: Tailwind                           = this
  def divideGray7: Tailwind                           = this
  def divideGray8: Tailwind                           = this
  def divideGray9: Tailwind                           = this
  def divideDanger1: Tailwind                         = this
  def divideDanger2: Tailwind                         = this
  def divideDanger3: Tailwind                         = this
  def divideDanger4: Tailwind                         = this
  def divideDanger5: Tailwind                         = this
  def dividePrimary1: Tailwind                        = this
  def dividePrimary2: Tailwind                        = this
  def dividePrimary3: Tailwind                        = this
  def dividePrimary4: Tailwind                        = this
  def dividePrimary5: Tailwind                        = this
  def divideSuccess1: Tailwind                        = this
  def divideSuccess2: Tailwind                        = this
  def divideSuccess3: Tailwind                        = this
  def divideSuccess4: Tailwind                        = this
  def divideSuccess5: Tailwind                        = this
  def divideWarning1: Tailwind                        = this
  def divideWarning2: Tailwind                        = this
  def divideWarning3: Tailwind                        = this
  def divideWarning4: Tailwind                        = this
  def divideWarning5: Tailwind                        = this
  def divideTransparent: Tailwind                     = this
  def divideCurrent: Tailwind                         = this
  def divideInherit: Tailwind                         = this
  def divideCustom1: Tailwind                         = this
  def divideCustom2: Tailwind                         = this
  def divideCustom3: Tailwind                         = this
  def divideCustom4: Tailwind                         = this
  def divideOpacity0: Tailwind                        = this
  def divideOpacity10: Tailwind                       = this
  def divideOpacity20: Tailwind                       = this
  def divideOpacity30: Tailwind                       = this
  def divideOpacity40: Tailwind                       = this
  def divideOpacity50: Tailwind                       = this
  def divideOpacity60: Tailwind                       = this
  def divideOpacity70: Tailwind                       = this
  def divideOpacity80: Tailwind                       = this
  def divideOpacity90: Tailwind                       = this
  def divideOpacity100: Tailwind                      = this
  def overflowAuto: Tailwind                          = this
  def overflowHidden: Tailwind                        = this
  def overflowClip: Tailwind                          = this
  def overflowVisible: Tailwind                       = this
  def overflowScroll: Tailwind                        = this
  def overflowXAuto: Tailwind                         = this
  def overflowYAuto: Tailwind                         = this
  def overflowXHidden: Tailwind                       = this
  def overflowYHidden: Tailwind                       = this
  def overflowXClip: Tailwind                         = this
  def overflowYClip: Tailwind                         = this
  def overflowXVisible: Tailwind                      = this
  def overflowYVisible: Tailwind                      = this
  def overflowXScroll: Tailwind                       = this
  def overflowYScroll: Tailwind                       = this
  def truncate: Tailwind                              = this
  def whitespaceNormal: Tailwind                      = this
  def whitespaceNowrap: Tailwind                      = this
  def whitespacePre: Tailwind                         = this
  def whitespacePreLine: Tailwind                     = this
  def whitespacePreWrap: Tailwind                     = this
  def whitespaceBreakSpaces: Tailwind                 = this
  def textWrap: Tailwind                              = this
  def textNowrap: Tailwind                            = this
  def textBalance: Tailwind                           = this
  def textPretty: Tailwind                            = this
  def breakNormal: Tailwind                           = this
  def breakWords: Tailwind                            = this
  def breakAll: Tailwind                              = this
  def breakKeep: Tailwind                             = this
  def rounded0: Tailwind                              = this
  def rounded2: Tailwind                              = this
  def rounded3: Tailwind                              = this
  def rounded4: Tailwind                              = this
  def rounded6: Tailwind                              = this
  def rounded8: Tailwind                              = this
  def rounded12: Tailwind                             = this
  def roundedFull: Tailwind                           = this
  def roundedT0: Tailwind                             = this
  def roundedR0: Tailwind                             = this
  def roundedB0: Tailwind                             = this
  def roundedL0: Tailwind                             = this
  def borderAll: Tailwind                             = this
  def borderTop: Tailwind                             = this
  def borderRight: Tailwind                           = this
  def borderBottom: Tailwind                          = this
  def borderLeft: Tailwind                            = this
  def borderT: Tailwind                               = this
  def borderR: Tailwind                               = this
  def borderB: Tailwind                               = this
  def borderL: Tailwind                               = this
  def borderX: Tailwind                               = this
  def borderY: Tailwind                               = this
  def border: Tailwind                                = this
  def border1: Tailwind                               = this
  def border2: Tailwind                               = this
  def border3: Tailwind                               = this
  def border4: Tailwind                               = this
  def borderSolid: Tailwind                           = this
  def borderDashed: Tailwind                          = this
  def borderDotted: Tailwind                          = this
  def borderDouble: Tailwind                          = this
  def borderHidden: Tailwind                          = this
  def borderNone: Tailwind                            = this
  def borderGray0: Tailwind                           = this
  def borderGray1: Tailwind                           = this
  def borderGray2: Tailwind                           = this
  def borderGray3: Tailwind                           = this
  def borderGray4: Tailwind                           = this
  def borderGray5: Tailwind                           = this
  def borderGray6: Tailwind                           = this
  def borderGray7: Tailwind                           = this
  def borderGray8: Tailwind                           = this
  def borderGray9: Tailwind                           = this
  def borderDanger1: Tailwind                         = this
  def borderDanger2: Tailwind                         = this
  def borderDanger3: Tailwind                         = this
  def borderDanger4: Tailwind                         = this
  def borderDanger5: Tailwind                         = this
  def borderPrimary1: Tailwind                        = this
  def borderPrimary2: Tailwind                        = this
  def borderPrimary3: Tailwind                        = this
  def borderPrimary4: Tailwind                        = this
  def borderPrimary5: Tailwind                        = this
  def borderSuccess1: Tailwind                        = this
  def borderSuccess2: Tailwind                        = this
  def borderSuccess3: Tailwind                        = this
  def borderSuccess4: Tailwind                        = this
  def borderSuccess5: Tailwind                        = this
  def borderWarning1: Tailwind                        = this
  def borderWarning2: Tailwind                        = this
  def borderWarning3: Tailwind                        = this
  def borderWarning4: Tailwind                        = this
  def borderWarning5: Tailwind                        = this
  def borderTransparent: Tailwind                     = this
  def borderCurrent: Tailwind                         = this
  def borderInherit: Tailwind                         = this
  def borderCustom1: Tailwind                         = this
  def borderCustom2: Tailwind                         = this
  def borderCustom3: Tailwind                         = this
  def borderCustom4: Tailwind                         = this
  def borderOpacity0: Tailwind                        = this
  def borderOpacity5: Tailwind                        = this
  def borderOpacity10: Tailwind                       = this
  def borderOpacity20: Tailwind                       = this
  def borderOpacity30: Tailwind                       = this
  def borderOpacity40: Tailwind                       = this
  def borderOpacity50: Tailwind                       = this
  def borderOpacity60: Tailwind                       = this
  def borderOpacity70: Tailwind                       = this
  def borderOpacity80: Tailwind                       = this
  def borderOpacity90: Tailwind                       = this
  def borderOpacity100: Tailwind                      = this
  def bgGray0: Tailwind                               = this
  def bgGray1: Tailwind                               = this
  def bgGray2: Tailwind                               = this
  def bgGray3: Tailwind                               = this
  def bgGray4: Tailwind                               = this
  def bgGray5: Tailwind                               = this
  def bgGray6: Tailwind                               = this
  def bgGray7: Tailwind                               = this
  def bgGray8: Tailwind                               = this
  def bgGray9: Tailwind                               = this
  def bgDanger1: Tailwind                             = this
  def bgDanger2: Tailwind                             = this
  def bgDanger3: Tailwind                             = this
  def bgDanger4: Tailwind                             = this
  def bgDanger5: Tailwind                             = this
  def bgPrimary1: Tailwind                            = this
  def bgPrimary2: Tailwind                            = this
  def bgPrimary3: Tailwind                            = this
  def bgPrimary4: Tailwind                            = this
  def bgPrimary5: Tailwind                            = this
  def bgSuccess1: Tailwind                            = this
  def bgSuccess2: Tailwind                            = this
  def bgSuccess3: Tailwind                            = this
  def bgSuccess4: Tailwind                            = this
  def bgSuccess5: Tailwind                            = this
  def bgWarning1: Tailwind                            = this
  def bgWarning2: Tailwind                            = this
  def bgWarning3: Tailwind                            = this
  def bgWarning4: Tailwind                            = this
  def bgWarning5: Tailwind                            = this
  def bgTransparent: Tailwind                         = this
  def bgCurrent: Tailwind                             = this
  def bgInherit: Tailwind                             = this
  def bgCustom1: Tailwind                             = this
  def bgCustom2: Tailwind                             = this
  def bgCustom3: Tailwind                             = this
  def bgCustom4: Tailwind                             = this
  def bgOpacity0: Tailwind                            = this
  def bgOpacity5: Tailwind                            = this
  def bgOpacity10: Tailwind                           = this
  def bgOpacity20: Tailwind                           = this
  def bgOpacity30: Tailwind                           = this
  def bgOpacity40: Tailwind                           = this
  def bgOpacity50: Tailwind                           = this
  def bgOpacity60: Tailwind                           = this
  def bgOpacity70: Tailwind                           = this
  def bgOpacity80: Tailwind                           = this
  def bgOpacity90: Tailwind                           = this
  def bgOpacity100: Tailwind                          = this
  def p0: Tailwind                                    = this
  def p2: Tailwind                                    = this
  def p4: Tailwind                                    = this
  def p6: Tailwind                                    = this
  def p8: Tailwind                                    = this
  def p12: Tailwind                                   = this
  def p16: Tailwind                                   = this
  def p20: Tailwind                                   = this
  def p24: Tailwind                                   = this
  def p32: Tailwind                                   = this
  def p40: Tailwind                                   = this
  def p48: Tailwind                                   = this
  def px0: Tailwind                                   = this
  def px2: Tailwind                                   = this
  def px4: Tailwind                                   = this
  def px6: Tailwind                                   = this
  def px8: Tailwind                                   = this
  def px12: Tailwind                                  = this
  def px16: Tailwind                                  = this
  def px20: Tailwind                                  = this
  def px24: Tailwind                                  = this
  def px32: Tailwind                                  = this
  def px40: Tailwind                                  = this
  def px48: Tailwind                                  = this
  def py0: Tailwind                                   = this
  def py2: Tailwind                                   = this
  def py4: Tailwind                                   = this
  def py6: Tailwind                                   = this
  def py8: Tailwind                                   = this
  def py12: Tailwind                                  = this
  def py16: Tailwind                                  = this
  def py20: Tailwind                                  = this
  def py24: Tailwind                                  = this
  def py32: Tailwind                                  = this
  def py40: Tailwind                                  = this
  def py48: Tailwind                                  = this
  def pt0: Tailwind                                   = this
  def pt2: Tailwind                                   = this
  def pt4: Tailwind                                   = this
  def pt6: Tailwind                                   = this
  def pt8: Tailwind                                   = this
  def pt12: Tailwind                                  = this
  def pt16: Tailwind                                  = this
  def pt20: Tailwind                                  = this
  def pt24: Tailwind                                  = this
  def pt32: Tailwind                                  = this
  def pt40: Tailwind                                  = this
  def pt48: Tailwind                                  = this
  def pr0: Tailwind                                   = this
  def pr2: Tailwind                                   = this
  def pr4: Tailwind                                   = this
  def pr6: Tailwind                                   = this
  def pr8: Tailwind                                   = this
  def pr12: Tailwind                                  = this
  def pr16: Tailwind                                  = this
  def pr20: Tailwind                                  = this
  def pr24: Tailwind                                  = this
  def pr32: Tailwind                                  = this
  def pr40: Tailwind                                  = this
  def pr48: Tailwind                                  = this
  def pb0: Tailwind                                   = this
  def pb2: Tailwind                                   = this
  def pb4: Tailwind                                   = this
  def pb6: Tailwind                                   = this
  def pb8: Tailwind                                   = this
  def pb12: Tailwind                                  = this
  def pb16: Tailwind                                  = this
  def pb20: Tailwind                                  = this
  def pb24: Tailwind                                  = this
  def pb32: Tailwind                                  = this
  def pb40: Tailwind                                  = this
  def pb48: Tailwind                                  = this
  def pl0: Tailwind                                   = this
  def pl2: Tailwind                                   = this
  def pl4: Tailwind                                   = this
  def pl6: Tailwind                                   = this
  def pl8: Tailwind                                   = this
  def pl12: Tailwind                                  = this
  def pl16: Tailwind                                  = this
  def pl20: Tailwind                                  = this
  def pl24: Tailwind                                  = this
  def pl32: Tailwind                                  = this
  def pl40: Tailwind                                  = this
  def pl48: Tailwind                                  = this
  def textLeft: Tailwind                              = this
  def textCenter: Tailwind                            = this
  def textRight: Tailwind                             = this
  def textJustify: Tailwind                           = this
  def textStart: Tailwind                             = this
  def textEnd: Tailwind                               = this
  def alignBaseline: Tailwind                         = this
  def alignTop: Tailwind                              = this
  def alignMiddle: Tailwind                           = this
  def alignBottom: Tailwind                           = this
  def alignTextTop: Tailwind                          = this
  def alignTextBottom: Tailwind                       = this
  def alignSub: Tailwind                              = this
  def alignSuper: Tailwind                            = this
  def fontSans: Tailwind                              = this
  def fontMono: Tailwind                              = this
  def text9: Tailwind                                 = this
  def text10: Tailwind                                = this
  def text11: Tailwind                                = this
  def text13: Tailwind                                = this
  def text15: Tailwind                                = this
  def text17: Tailwind                                = this
  def text20: Tailwind                                = this
  def text23: Tailwind                                = this
  def text26: Tailwind                                = this
  def text30: Tailwind                                = this
  def text35: Tailwind                                = this

  /** {{{font-weight: 400}}}
    */
  def fontNormal: Tailwind = this

  /** {{{font-weight: 500}}}
    */
  def fontMedium: Tailwind = this

  /** {{{font-weight: 600}}}
    */
  def fontSemiBold: Tailwind = this

  /** {{{font-weight: 700}}}
    */
  def fontBold: Tailwind        = this
  def uppercase: Tailwind       = this
  def capitalize: Tailwind      = this
  def normalCase: Tailwind      = this
  def italic: Tailwind          = this
  def slashedZero: Tailwind     = this
  def tabularNums: Tailwind     = this
  def leading16: Tailwind       = this
  def leading20: Tailwind       = this
  def leading24: Tailwind       = this
  def leading28: Tailwind       = this
  def leading32: Tailwind       = this
  def leading40: Tailwind       = this
  def leading44: Tailwind       = this
  def leadingR1p5: Tailwind     = this
  def textGray0: Tailwind       = this
  def textGray1: Tailwind       = this
  def textGray2: Tailwind       = this
  def textGray3: Tailwind       = this
  def textGray4: Tailwind       = this
  def textGray5: Tailwind       = this
  def textGray6: Tailwind       = this
  def textGray7: Tailwind       = this
  def textGray8: Tailwind       = this
  def textGray9: Tailwind       = this
  def textDanger1: Tailwind     = this
  def textDanger2: Tailwind     = this
  def textDanger3: Tailwind     = this
  def textDanger4: Tailwind     = this
  def textDanger5: Tailwind     = this
  def textPrimary1: Tailwind    = this
  def textPrimary2: Tailwind    = this
  def textPrimary3: Tailwind    = this
  def textPrimary4: Tailwind    = this
  def textPrimary5: Tailwind    = this
  def textSuccess1: Tailwind    = this
  def textSuccess2: Tailwind    = this
  def textSuccess3: Tailwind    = this
  def textSuccess4: Tailwind    = this
  def textSuccess5: Tailwind    = this
  def textWarning1: Tailwind    = this
  def textWarning2: Tailwind    = this
  def textWarning3: Tailwind    = this
  def textWarning4: Tailwind    = this
  def textWarning5: Tailwind    = this
  def textTransparent: Tailwind = this
  def textCurrent: Tailwind     = this
  def textInherit: Tailwind     = this
  def textCustom1: Tailwind     = this
  def textCustom2: Tailwind     = this
  def textCustom3: Tailwind     = this
  def textCustom4: Tailwind     = this
  def textOpacity0: Tailwind    = this
  def textOpacity10: Tailwind   = this
  def textOpacity20: Tailwind   = this
  def textOpacity30: Tailwind   = this
  def textOpacity40: Tailwind   = this
  def textOpacity50: Tailwind   = this
  def textOpacity60: Tailwind   = this
  def textOpacity70: Tailwind   = this
  def textOpacity80: Tailwind   = this
  def textOpacity90: Tailwind   = this
  def textOpacity100: Tailwind  = this
  def underline: Tailwind       = this
  def lineThrough: Tailwind     = this
  def noUnderline: Tailwind     = this
  def opacity0: Tailwind        = this
  def opacity10: Tailwind       = this
  def opacity20: Tailwind       = this
  def opacity30: Tailwind       = this
  def opacity40: Tailwind       = this
  def opacity50: Tailwind       = this
  def opacity60: Tailwind       = this
  def opacity70: Tailwind       = this
  def opacity80: Tailwind       = this
  def opacity90: Tailwind       = this
  def opacity100: Tailwind      = this
  def shadow1: Tailwind         = this
  def shadow2: Tailwind         = this
  def shadow3: Tailwind         = this
  def shadow4: Tailwind         = this
  def shadowSpread: Tailwind    = this
  def objectCover: Tailwind     = this
  // custom css classes
  def trnsA: Tailwind    = this
  def trnsO: Tailwind    = this
  def trnsS: Tailwind    = this
  def listNone: Tailwind = this

  /** {{{
    *  font-size: 23px;
    *  line-height: 32px;
    *  font-weight: 700;
    * }}}
    */
  def heading1: Tailwind = this

  /** {{{
    *  font-size: 20px;
    *  line-height: 32px;
    *  font-weight: 700;
    * }}}
    */
  def heading2: Tailwind = this

  /** {{{
    *  font-size: 17px;
    *  line-height: 28px;
    *  font-weight: 700;
    * }}}
    */
  def heading3: Tailwind = this

  /** {{{
    *  font-size: 15px;
    *  line-height: 24px;
    *  font-weight: 700;
    * }}}
    */
  def heading4: Tailwind = this

  /** {{{
    *  font-size: 13px;
    *  line-height: 20px;
    *  font-weight: 700;
    * }}}
    */
  def heading5: Tailwind = this

  /** {{{
    *  font-size: 15px;
    *  line-height: 20px;
    *  font-weight: 400;
    * }}}
    */
  def textBodyLarge: Tailwind = this

  /** {{{
    *  font-size: 13px;
    *  line-height: 20px;
    *  font-weight: 400;
    * }}}
    */
  def textBody: Tailwind = this

  /** {{{
    *  font-size: 11px;
    *  line-height: 26px;
    *  font-weight: 400;
    * }}}
    */
  def textSmall: Tailwind = this

  /** {{{
    *  font-size: 10px;
    *  line-height: 16px;
    *  font-weight: 400;
    * }}}
    */
  def textTiny: Tailwind = this

  /** {{{
    *  font-size: 10px;
    *  line-height: 16px;
    *  font-weight: 500;
    *  letter-spacing: 0.12em;
    * }}}
    */
  def textOverline: Tailwind             = this
  def outlineNone: Tailwind              = this
  def outlineLight: Tailwind             = this
  def outlineDark: Tailwind              = this
  def flexCenter: Tailwind               = this
  def inlineFlexCenter: Tailwind         = this
  def anTx330: Tailwind                  = this
  def anCircle: Tailwind                 = this
  def anPulse: Tailwind                  = this
  def anFadeIn: Tailwind                 = this
  def anFadeout: Tailwind                = this
  def aclAnimationFlash: Tailwind        = this
  def aclAnimationSlideInDown: Tailwind  = this
  def aclAnimationSlideInUp: Tailwind    = this
  def aclAnimationSlideInLeft: Tailwind  = this
  def aclAnimationSlideInRight: Tailwind = this
  def aclAnimationSlideOutLtr: Tailwind  = this
  def aclAnimationSlideOutRtl: Tailwind  = this
  def alignInherit: Tailwind             = this
  // Negative classes
  private def _m8: Tailwind = this // Required so that Tailwind CLI can detect and extract this utility class.
  def negativeM8: Tailwind  = this

  // Semantic CSS classes used by special components excluded by themes
  def bgSemanticGray0: Tailwind    = this
  def bgSemanticGray1: Tailwind    = this
  def bgSemanticGray2: Tailwind    = this
  def bgSemanticGray3: Tailwind    = this
  def bgSemanticGray4: Tailwind    = this
  def bgSemanticGray5: Tailwind    = this
  def bgSemanticGray6: Tailwind    = this
  def bgSemanticGray7: Tailwind    = this
  def bgSemanticGray8: Tailwind    = this
  def bgSemanticGray9: Tailwind    = this
  def bgSemanticDanger1: Tailwind  = this
  def bgSemanticDanger2: Tailwind  = this
  def bgSemanticDanger3: Tailwind  = this
  def bgSemanticDanger4: Tailwind  = this
  def bgSemanticDanger5: Tailwind  = this
  def bgSemanticPrimary1: Tailwind = this
  def bgSemanticPrimary2: Tailwind = this
  def bgSemanticPrimary3: Tailwind = this
  def bgSemanticPrimary4: Tailwind = this
  def bgSemanticPrimary5: Tailwind = this
  def bgSemanticSuccess1: Tailwind = this
  def bgSemanticSuccess2: Tailwind = this
  def bgSemanticSuccess3: Tailwind = this
  def bgSemanticSuccess4: Tailwind = this
  def bgSemanticSuccess5: Tailwind = this
  def bgSemanticWarning1: Tailwind = this
  def bgSemanticWarning2: Tailwind = this
  def bgSemanticWarning3: Tailwind = this
  def bgSemanticWarning4: Tailwind = this
  def bgSemanticWarning5: Tailwind = this

  def borderSemanticGray0: Tailwind    = this
  def borderSemanticGray1: Tailwind    = this
  def borderSemanticGray2: Tailwind    = this
  def borderSemanticGray3: Tailwind    = this
  def borderSemanticGray4: Tailwind    = this
  def borderSemanticGray5: Tailwind    = this
  def borderSemanticGray6: Tailwind    = this
  def borderSemanticGray7: Tailwind    = this
  def borderSemanticGray8: Tailwind    = this
  def borderSemanticGray9: Tailwind    = this
  def borderSemanticDanger1: Tailwind  = this
  def borderSemanticDanger2: Tailwind  = this
  def borderSemanticDanger3: Tailwind  = this
  def borderSemanticDanger4: Tailwind  = this
  def borderSemanticDanger5: Tailwind  = this
  def borderSemanticPrimary1: Tailwind = this
  def borderSemanticPrimary2: Tailwind = this
  def borderSemanticPrimary3: Tailwind = this
  def borderSemanticPrimary4: Tailwind = this
  def borderSemanticPrimary5: Tailwind = this
  def borderSemanticSuccess1: Tailwind = this
  def borderSemanticSuccess2: Tailwind = this
  def borderSemanticSuccess3: Tailwind = this
  def borderSemanticSuccess4: Tailwind = this
  def borderSemanticSuccess5: Tailwind = this
  def borderSemanticWarning1: Tailwind = this
  def borderSemanticWarning2: Tailwind = this
  def borderSemanticWarning3: Tailwind = this
  def borderSemanticWarning4: Tailwind = this
  def borderSemanticWarning5: Tailwind = this

  def textSemanticGray0: Tailwind    = this
  def textSemanticGray1: Tailwind    = this
  def textSemanticGray2: Tailwind    = this
  def textSemanticGray3: Tailwind    = this
  def textSemanticGray4: Tailwind    = this
  def textSemanticGray5: Tailwind    = this
  def textSemanticGray6: Tailwind    = this
  def textSemanticGray7: Tailwind    = this
  def textSemanticGray8: Tailwind    = this
  def textSemanticGray9: Tailwind    = this
  def textSemanticDanger1: Tailwind  = this
  def textSemanticDanger2: Tailwind  = this
  def textSemanticDanger3: Tailwind  = this
  def textSemanticDanger4: Tailwind  = this
  def textSemanticDanger5: Tailwind  = this
  def textSemanticPrimary1: Tailwind = this
  def textSemanticPrimary2: Tailwind = this
  def textSemanticPrimary3: Tailwind = this
  def textSemanticPrimary4: Tailwind = this
  def textSemanticPrimary5: Tailwind = this
  def textSemanticSuccess1: Tailwind = this
  def textSemanticSuccess2: Tailwind = this
  def textSemanticSuccess3: Tailwind = this
  def textSemanticSuccess4: Tailwind = this
  def textSemanticSuccess5: Tailwind = this
  def textSemanticWarning1: Tailwind = this
  def textSemanticWarning2: Tailwind = this
  def textSemanticWarning3: Tailwind = this
  def textSemanticWarning4: Tailwind = this
  def textSemanticWarning5: Tailwind = this
}
